name: 0.0.$(Date:yyMM.d)$(Rev:rrr)

variables:
  System.Debug: true

trigger:
  branches:  # branch conditions to filter the events, optional; Defaults to all branches.
    include: [ "master" ]  
pr: none

jobs:
  - job: Test
    pool:
      vmImage: windows-2019
    timeoutInMinutes: 120
    cancelTimeoutInMinutes: 5
    steps:
      - checkout: self
        clean: true
        submodules: false

      - task: NodeTool@0
        displayName: Use node 8
        inputs:
          versionSpec: "8.x"

      - script: npm i -g npm@6.9.0 --force
        displayName: Use npm version 6.9.0

      - script: npm install

      - script: node make.js build --task PublishSymbolsV2

      # - script: dir /s/b

      # - task: PublishPipelineArtifact@1
      #   displayName: "Publish artifacts"
      #   inputs:
      #     targetPath: _build\Tasks\PublishSymbolsV2
      #     artifactName: "PublishSymbolV2"

      - powershell: |
          $env:System_Culture = "en-US"
          . .\Tests\lib\Initialize-Test.ps1
          Import-Module -Name .\_build\Tasks\PublishSymbolsV2\ps_modules\VstsTaskSdk\VstsTaskSdk.psm1 -Verbose -ArgumentList @{'NonInteractive' = 'true'}
          $env:Agent_HomeDirectory = "D:\Downloads\vsts-agent-win7-x64-2.117.1"
          $env:PublishSymbolsV2_Debug = "true"
          $env:PublishSymbolsV2_UseDbgLkg = "true"
          $env:INPUT_symbolServerType = "TeamServices"
          $env:INPUT_SearchPattern = "testData/**"
          Write-Verbose "GOT HERE"
          global:Invoke-VstsTaskScript -ScriptBlock { . .\_build\Tasks\PublishSymbolsV2\PublishSymbols.ps1 }
