name: 0.0.$(Date:yyMM.d)$(Rev:rrr)

trigger: none
pr: none

jobs:
  - job: Test
    pool:
      vmImage: windows-2019
    timeoutInMinutes: 120
    cancelTimeoutInMinutes: 5
    steps:
      - checkout: self
        clean: true
        submodules: false
      - task: NodeTool@0
        displayName: Use node 8
        inputs:
          versionSpec: "8.x"

      - script: npm i -g npm@6.9.0 --force
        displayName: Use npm version 6.9.0
      - script: npm install
      - script: node make.js build --task PublishSymbolsV2
      - script: dir /s/b
